name: Docker Image CI

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  USERNAME: anas790
  IMAGE_NAME: ${{ github.repository }}
  PLATFORMS: linux/amd64,linux/arm64/v8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the tagged commit
      uses: actions/checkout@v2

    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu'
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          /tmp/.buildx-cache
        key: ${{ runner.os }}-gradle-jdk17-${{ hashFiles('**/*gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-jdk17
          
    - name: Build Spring Boot application
      working-directory: ./highmed
      run: ./gradlew shadowJar
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        file: Dockerfile
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        platforms: ${{ env.PLATFORMS }}
    
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache